<?php

/**
 * @file
 * Ethnography support for Islandora.
 */

/**
 * Implements hook_theme().
 */
function islandora_ethnography_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_person_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-person',
      'pattern' => 'islandora_person__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_dept_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-dept',
      'pattern' => 'islandora_dept__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

function islandora_ethnography_islandora_personCmodel_islandora_view_object_alter(&$object, &$rendered) {
  unset($rendered['']);

  return 'foo';
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_personCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_person_ethnography', array('object' => $object));
  return array('islandora_ethnography' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_organizationCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_dept_ethnography', array('object' => $object));
  return array('islandora_ethnography' => $output);
}

