<?php
/**
 * @file
 * Islandora module for ethnography with customizations
 */

define('ISLANDORA_ETHNOGRAPHY_CIDOC', 'http://www.cidoc-crm.org/cidoc-crm/');
define('ISLANDORA_ETHNOGRAPHY_FRBROO', 'http://iflastandards.info/ns/fr/frbr/frbroo/');

/**
 * @file
 * Ethnography support for Islandora.
 */

/**
 * Implements hook_theme().
 */
function islandora_ethnography_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_person_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-person',
      'pattern' => 'islandora_person__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_dept_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-dept',
      'pattern' => 'islandora_dept__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_tune_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-tune',
      'pattern' => 'islandora_tune__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_notation_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-notation',
      'pattern' => 'islandora_notation__',
      'variables' => array('object' => NULL),
    ),
    'islandora_story_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-story',
      'pattern' => 'islandora_story__',
      'variables' => array('object' => NULL),
    ),
    'islandora_video_ethnography' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-video-eth',
      'pattern' => 'islandora_video__',
      'variables' => array('object' => NULL),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_ethnography_menu() {
  return array(
    'islandora/object/%islandora_object_bio/edit_bio' => array(
      'title' => 'Edit Bio Text',
      'page callback' => 'islandora_edit_datastream',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/datastream.inc',
      'file path' => drupal_get_path('module', 'islandora'),
      'access callback' => 'islandora_datastream_access',
      'access arguments' => array(ISLANDORA_METADATA_EDIT, 2),
    ),
    'islandora/object/%islandora_object_obj/edit_obj' => array(
      'title' => 'Edit Text',
      'page callback' => 'islandora_edit_datastream',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/datastream.inc',
      'file path' => drupal_get_path('module', 'islandora'),
      'access callback' => 'islandora_ethnography_edit_story',
      'access arguments' => array(ISLANDORA_METADATA_EDIT, 2),
    ),
  );
}

function islandora_object_bio_load($pid) {
  $object = islandora_object_load($pid);
  return $object['BIO'];
}

function islandora_object_obj_load($pid) {
  $object = islandora_object_load($pid);
  return $object['OBJ'];
}

function islandora_ethnography_edit_story($op, $datastream) {
  if (!in_array('islandora:storyCModel', $datastream->parent->models)) {
    return FALSE;
  }
  else {
    return islandora_datastream_access($op, $datastream);
  }
}
/**
 * Implements hook_CMODEL_PID_islandora_view_object_alter().
 */
function islandora_ethnography_islandora_organizationCModel_islandora_view_object_alter(&$object, &$rendered) {
  unset($rendered['']);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object_alter().
 */
function islandora_ethnography_islandora_personCModel_islandora_view_object_alter(&$object, &$rendered) {
  unset($rendered['']);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_personCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_person_ethnography', array('object' => $object));
  return array('islandora_ethnography' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_organizationCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_dept_ethnography', array('object' => $object));
  return array('islandora_ethnography' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_BDHTuneCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_tune_ethnography', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_BDHNotationCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_notation_ethnography', array('object' => $object));
  return array('' => $output);
}
/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_islandora_storyCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_story_ethnography', array('object' => $object));
  return array('' => $output);
}
/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_audio_bdh_audioSnippetCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_audio', array('islandora_object' => $object));
  return array('' => $output);
}
/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_bdh_videoCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_video_ethnography', array('object' => $object));
  return array('' => $output);
}
/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_ethnography_bdh_videoSnippetCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_video_ethnography', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_ethnography_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_ethnography');

  // Tune Content Model.
  $tune_content_model = $connection->repository->constructObject('islandora:BDHTuneCModel');
  $tune_content_model->owner = 'fedoraAdmin';
  $tune_content_model->label = 'Islandora Tune Work Content Model';
  $tune_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_ethnography_ingest__ds_composite_datastream($tune_content_model, $module_path . "/xml/islandora_tune_ds_composite_model.xml");

  // Notation Content Model.
  $notation_content_model = $connection->repository->constructObject('islandora:BDHNotationCModel');
  $notation_content_model->owner = 'fedoraAdmin';
  $notation_content_model->label = 'Islandora Music Notation Content Model';
  $notation_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_ethnography_ingest__ds_composite_datastream($notation_content_model, $module_path . "/xml/islandora_notation_ds_composite_model.xml");
  
  
  // Story Content Model.
  $story_content_model = $connection->repository->constructObject('islandora:storyCModel');
  $story_content_model->owner = 'fedoraAdmin';
  $story_content_model->label = 'Islandora Story Content Model';
  $story_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_ethnography_ingest__ds_composite_datastream($notation_content_model, $module_path . "/xml/islandora_story_ds_composite_model.xml");
  
  // video Content Model.
  $video_content_model = $connection->repository->constructObject('islandora:videoSnippetCModel');
  $video_content_model->owner = 'fedoraAdmin';
  $video_content_model->label = 'Islandora Video Content Model';
  $video_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_ethnography_ingest__ds_composite_datastream($notation_content_model, $module_path . "/xml/islandora_video_snippet_ds_composite_model.xml");

  /*
  // Tune Collection.
  $entity_collection = $connection->repository->constructObject('islandora:tune_work_collection');
  $entity_collection->owner = 'fedoraAdmin';
  $entity_collection->label = 'Tune Collection';
  $entity_collection->models = 'islandora:collectionCModel';
  $entity_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $thumbnail_datastream = $entity_collection->constructDatastream('TN', 'M');
  $thumbnail_datastream->label = 'Thumbnail';
  $thumbnail_datastream->mimetype = 'image/png';
  $thumbnail_datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $entity_collection->ingestDatastream($thumbnail_datastream);
  // Collection policy datastream.
  $collection_policy_datastream = $entity_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $collection_policy_datastream->label = 'Collection policy';
  $collection_policy_datastream->mimetype = 'text/xml';
  $collection_policy_datastream->setContentFromFile("$module_path/xml/islandora_entity_collection_policy.xml", FALSE);
  $entity_collection->ingestDatastream($collection_policy_datastream);
  */

  return array(
    'islandora_ethnography' => array(
      'title' => 'Islandora ethnography',
      'objects' => array(
        $tune_content_model,
        $notation_content_model,
        $story_content_model,
        $video_content_model,
      ),
    ),
  );
}

/**
 * This function will add an entity DS composite datastream to an object.
 *
 * This is a workaround of a known issue with temp files being lost in Tuque in
 * batches because of object destruction during the serialization process.
 *
 * @param AbstractObject $islandora_object
 *   The object to add the DS composite datastream to.
 */
function islandora_ethnography_ingest__ds_composite_datastream(AbstractObject $islandora_object, $filename) {
  $module_path = drupal_get_path('module', 'islandora_ethnography');

  $ds_composite_datastream = $islandora_object->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ds_composite_datastream->label = 'DS-COMPOSITE-MODEL';
  $ds_composite_datastream->mimetype = 'text/xml';
  $ds_composite_datastream->setContentFromFile($filename, FALSE);
  $islandora_object->ingestDatastream($ds_composite_datastream);
}

/**
 * Get local thumbnail.
 */
function islandora_ethnography_get_default_thumbnail($cmodel) {
  $base_path = drupal_get_path('module', 'islandora_ethnography');
  switch ($cmodel) {
    case 'bdh:audioSnippetCModel':
      return $base_path . '/images/music-snippet.png';

    case 'islandora:BDHTuneCModel':
      return $base_path . '/images/music-work.png';

    case 'islandora:BDHNotationCModel':
      return $base_path . '/images/music-document.png';

    case 'islandora:personCModel':
      return $base_path . '/images/person.png';

    case 'islandora:organizationCModel':
      return $base_path . '/images/group.png';

  }
  return '';
}

/**
 * Implements hook_islandora_CMODEL_PID_islandora_solr_object_result_alter().
 */
function islandora_ethnography_bdh_audioSnippetCModel_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  $search_result['thumbnail_url'] = drupal_get_path('module', 'islandora_ethnography') . '/images/music-snippet.png';
}

/**
 * Implements hook_islandora_CMODEL_PID_islandora_solr_object_result_alter().
 */
function islandora_ethnography_islandora_BDHTuneCModel_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  $search_result['thumbnail_url'] = drupal_get_path('module', 'islandora_ethnography') . '/images/music-work.png';
}
/**
 * Implements hook_islandora_CMODEL_PID_islandora_solr_object_result_alter().
 */
function islandora_ethnography_islandora_BDHNotationCModel_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  $search_result['thumbnail_url'] = drupal_get_path('module', 'islandora_ethnography') . '/images/music-document.png';
}

/**
 * Implements hook_islandora_CMODEL_PID_islandora_solr_object_result_alter().
 */
function islandora_ethnography_islandora_PersonCModel_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  $search_result['thumbnail_url'] = drupal_get_path('module', 'islandora_ethnography') . '/images/person.png';
}

/**
 * Implements hook_islandora_CMODEL_PID_islandora_solr_object_result_alter().
 */
function islandora_ethnography_islandora_organizationCModel_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  $search_result['thumbnail_url'] = drupal_get_path('module', 'islandora_ethnography') . '/images/group.png';
}

/**
 * Implements hook_block_info().
 */
function islandora_ethnography_block_info() {
  $blocks['notation_is_expression_of'] = array(
    'info' => t('Islandora Ethnography Expression Of'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'islandora/object/*',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function islandora_ethnography_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'notation_is_expression_of':
      $block['subject'] = NULL;
      $block['content'] = islandora_ethnography_notation_block();
      break;
  }
  return $block;
}

function islandora_ethnography_notation_block() {
  $block = array();
  $object = menu_get_object('islandora_object', 2);
  if ($object) {
    if (in_array('islandora:BDHNotationCModel', $object->models)) {
      $block = array();
      $parents = $object->relationships->get('http://iflastandards.info/ns/fr/frbr/frbroo/', 'R3i_realises');
      foreach ($parents as $parent) {

        $parent_object = islandora_object_load($parent['object']['value']);
        $block['#markup'] = t('Is notation for the Tune Work !label', array(
          '!label' => l($parent_object->label, 'islandora/object/' . $parent_object->id ),
        ));

      }
      return $block;
    }

  }

}

/**
 * Implements hook_preprocess.
 */
function islandora_ethnography_preprocess_islandora_audio(&$variables) {

}

function islandora_ethnography_remove_format($form, &$form_state) {
  // Remove the format element, so objective_forms doesn't barf.
  unset($form_state['complete form']['Content']['format']);

  // Remove line endings from the value.
  $form_state['values']['Content']['value'] = str_replace("\r\n", '', $form_state['values']['Content']['value']);
  $form_state['values']['Content']['value'] = str_replace("&nbsp;", '', $form_state['values']['Content']['value']);
}

/**
 * Implements hook_process_THEME().
 */
function islandora_ethnography_process_islandora_solr_metadata_display(&$variables) {
  foreach ($variables['solr_fields'] as $fieldname => $data) {
    foreach ($data['value'] as $index => $value) {
      if (strpos($value, 'info:fedora') === 0) {
        $pid = substr($value, 12);
        $link = islandora_ethnography_get_object_link($pid);
        if ($link) {
          $variables['solr_fields'][$fieldname]['value'][$index] = $link;
        }
      }
    }
  }
}

/**
 * Return a link to the Islandora object.
 */
function islandora_ethnography_get_object_link($pid) {
  // FIXME cache this?.
  $query_processor = new IslandoraSolrQueryProcessor();
  $query_processor->solrQuery = 'PID:"' . $pid . '"';
  $query_processor->solrParams['fl'] = 'PID, fgs_label_s';
  $query_processor->executeQuery(FALSE);
  if ($query_processor->islandoraSolrResult['response']['numFound'] > 0) {
    $object_label = $query_processor->islandoraSolrResult['response']['objects']['0']['object_label'];
    $object_url = $query_processor->islandoraSolrResult['response']['objects']['0']['object_url'];
  }
  else {
    return '';
  }
  $link = l($object_label, $object_url, array());
  return $link;
}

/**
 * Implements hook_form_alter().
 */
function islandora_ethnography_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "contact_site_form") {
    array_unshift($form['#validate'], 'islandora_ethnography_contact_form_validate');
  }

}

/**
 * Custom validator for site form, adds the url of page from to the message.
 */
function islandora_ethnography_contact_form_validate($form, &$form_state) {
  if ($form_state['submitted'] == TRUE) {
    $referring_page = url($_GET['path'], array('absolute' => TRUE));
    $form_state['values']['message'] .= t("\n This message was sent in regard to the page at !referring_page.", array('!referring_page' => $referring_page));

  }
  return;
}
