<?php

/**
 * Implements hook_schema().
 */
function islandora_ethnography_schema() {
  $schema = array();
  $schema['cache_islandora_ethnography'] = drupal_get_schema_unprocessed('system', 'cache');
  return $schema;
}

/**
 * Adds all database functionality.
 */
function islandora_ethnography_update_7001(&$sandbox) {
  drupal_install_schema('islandora_ethnography');
  $t = get_t();
  return $t("Islandora ethnography caching updates complete.");
}

